version: '3.9'
services:
  mongodb:
    image: mongo:4
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]}).ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 30s
      start_period: 30s
    command: ['--replSet', 'rs0']
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: unless-stopped
    networks:
      - next
  next:
    build: .
    command: bash -c "prisma generate && npm run dev"
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - next

volumes:
  mongodb:
    driver: local

networks:
  next:
    name: next
